In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_excel(r"C:\Users\mushr\OneDrive\Desktop\PBI Dataset\Amazon Sales (5).xlsx")

ImportError: `Import openpyxl` failed.  Use pip or conda to install the openpyxl package.

In [12]:
df.shape

NameError: name 'df' is not defined

In [1]:
import sys
!{sys.executable} -m pip install --upgrade openpyxl

Requirement already satisfied: openpyxl in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import pandas as pd

In [2]:
df = pd.read_excel(r"C:\Users\mushr\OneDrive\Desktop\PBI Dataset\Amazon Sales (5).xlsx")

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\mushr\\OneDrive\\Desktop\\PBI Dataset\\Amazon Sales (5).xlsx'

In [13]:
df = pd.read_excel(r"C:\Users\mushr\OneDrive\Desktop\PBI Dataset\Amazon Sales.xlsx")

In [14]:
df.shape

(56046, 8)

In [15]:
df = df.ffill()

In [6]:
df.isnull().sum()

OrderDate        0
StockDate        0
OrderNumber      0
ProductKey       0
CustomerKey      0
TerritoryKey     0
OrderLineItem    0
OrderQuantity    0
dtype: int64

In [7]:
df.head(2)

,OrderDate,StockDate,OrderNumber,ProductKey,CustomerKey,TerritoryKey,OrderLineItem,OrderQuantity
0,2020-01-01,2019-09-21,SO45080,332,14657,1,1,1
1,2020-01-01,2019-12-05,SO45079,312,29255,4,1,1

In [16]:
df = pd.read_excel(r"C:\Users\mushr\OneDrive\Desktop\PBI Dataset\Superstore Unstructure.xlsx")

In [17]:
df.shape

(807, 7)

In [18]:
df = df.bfill()

In [11]:
df.isnull().sum()

Customer ID           0
First_Name            0
Last_Name             0
Segment               0
Country_State_City    0
Postal Code           0
Region                0
dtype: int64

In [19]:
df.head(2)

,Customer ID,First_Name,Last_Name,Segment,Country_State_City,Postal Code,Region
0,DP-13000,Darren,Powers,Consumer,United States_Texas_Houston,77095,Central
1,PO-19195,Phillina,Ober,Home Office,United States_Illinois_Naperville,60540,Central

In [20]:
df = pd.read_excel(r"C:\Users\mushr\Downloads\Financial_Sample.xlsx")

In [21]:
df.shape

(700, 16)

In [22]:
df = df.bfill()

In [16]:
df.isnull().sum()

Segment                0
Country                0
Product                0
Discount Band          0
Units Sold             0
Manufacturing Price    0
Sale Price             0
Gross Sales            0
Discounts              0
 Sales                 0
COGS                   0
Profit                 0
Date                   0
Month Number           0
Month Name             0
Year                   0
dtype: int64

In [23]:
df.head(2)

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Month Name,Year
0,Government,Canada,Carretera,Low,1618.5,3,20.0,32370.0,0.0,32370.0,16185.0,16185.0,2014-01-01,1,January,2014
1,Government,Germany,Carretera,Low,1321.0,3,20.0,26420.0,0.0,26420.0,13210.0,13210.0,2014-01-01,1,January,2014

In [18]:
df['Gross Sales'].max()

np.float64(1207500.0)

In [19]:
# Encoding
# Text Data type (Two Types)
# -Nprmal Text--Delhi,Noida,Mumbai,Goa,  (No Relationship)
# -Ordinal Text--Large,Medium,Small,Xls  (Relationship)

In [21]:
df.Product.unique()

<StringArray>
['Carretera', 'Montana', 'Paseo', 'Velo', 'VTT', 'Amarilla']
Length: 6, dtype: str

In [23]:
df['Discount Band'].unique()

<StringArray>
['Low', 'Medium', 'High']
Length: 3, dtype: str

In [24]:
# Encoding (Types)
# 1. oneHotEncoding
# 2. OrdinalEncoding
# 3. LabelEncoding

In [25]:
db = ['Low', 'Medium' , 'High']

In [28]:
df['Discount Band']

0       Low
1       Low
2       Low
3       Low
4       Low
       ...
695    High
696    High
697    High
698    High
699    High
Name: Discount Band, Length: 700, dtype: str

In [36]:
df['Discount Band'] = df['Discount Band'].map( lambda val:db.index(val) )

In [33]:
print(db)

['Discount Band']

In [34]:
print(df['Discount Band'].unique())

<StringArray>
['Low', 'Medium', 'High']
Length: 3, dtype: str

In [35]:
db = ['Low','Medium','High']

In [37]:
df['Discount Band']

0      0
1      0
2      0
3      0
4      0
      ..
695    2
696    2
697    2
698    2
699    2
Name: Discount Band, Length: 700, dtype: int64

In [39]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (1.9.0)
Requirement already satisfied: numpy>=1.24.1 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (2.3.5)
Requirement already satisfied: scipy>=1.10.0 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (1.18.0)
Requirement already satisfied: joblib>=1.4.0 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (2.24.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (3.6.0)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [43]:
df = pd.read_excel(r"C:\Users\mushr\Downloads\Financial_Sample.xlsx").bfill()

In [24]:
df['Discount Band']

0       Low
1       Low
2       Low
3       Low
4       Low
       ...
695    High
696    High
697    High
698    High
699    High
Name: Discount Band, Length: 700, dtype: str

In [45]:
from sklearn.preprocessing import OrdinalEncoder

In [47]:
encoder = OrdinalEncoder( categories = [['Low','Medium','High']] )

In [25]:
df['Discount Band'] = encoder.fit_transform(df[['Discount Band']])

C:\Users\mushr\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [49]:
df['Discount Band']

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ...
695    2.0
696    2.0
697    2.0
698    2.0
699    2.0
Name: Discount Band, Length: 700, dtype: float64

In [50]:
df['Country'].unique()

<StringArray>
['Canada', 'Germany', 'France', 'Mexico', 'United States of America']
Length: 5, dtype: str

In [52]:
df['Country'] = df['Country'].map(lambda val: list(df['Country'].unique()).index(val))

In [53]:
df['Country']

0      0
1      1
2      2
3      1
4      3
      ..
695    2
696    3
697    3
698    0
699    4
Name: Country, Length: 700, dtype: int64

In [5]:
from sklearn.preprocessing import LabelEncoder

In [6]:
encoder = LabelEncoder()

In [26]:
df['Country'] = encoder.fit_transform(df[['Country']])

C:\Users\mushr\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [57]:
df['Segment']

0            Government
1            Government
2             Midmarket
3             Midmarket
4             Midmarket
             ...
695      Small Business
696      Small Business
697          Government
698          Government
699    Channel Partners
Name: Segment, Length: 700, dtype: str

In [30]:
df['Segment'].unique()

<StringArray>
['Government', 'Midmarket', 'Channel Partners', 'Enterprise',
 'Small Business']
Length: 5, dtype: str

In [31]:
def OneHotEncoding(val):
    df[val] = df['Segment'].map(lambda seg:1 if seg == val else 0)

In [32]:
for val in df['Segment'].unique():
    OneHotEncoding(val)

In [65]:
df.shape

(700, 21)

In [66]:
df.head

<bound method NDFrame.head of               Segment  Country    Product  Discount Band  Units Sold  \
0          Government        0  Carretera            0.0      1618.5
1          Government        1  Carretera            0.0      1321.0
2           Midmarket        2  Carretera            0.0      2178.0
3           Midmarket        1  Carretera            0.0       888.0
4           Midmarket        3  Carretera            0.0      2470.0
..                ...      ...        ...            ...         ...
695    Small Business        2   Amarilla            2.0      2475.0
696    Small Business        3   Amarilla            2.0       546.0
697        Government        3    Montana            2.0      1368.0
698        Government        0      Paseo            2.0       723.0
699  Channel Partners        4        VTT            2.0      1806.0

     Manufacturing Price  Sale Price  Gross Sales  Discounts      Sales  ...  \
0                      3        20.0      32370.0       0.00   32370.00  ...
1                      3        20.0      26420.0       0.00   26420.00  ...
2                      3        15.0      32670.0       0.00   32670.00  ...
3                      3        15.0      13320.0       0.00   13320.00  ...
4                      3        15.0      37050.0       0.00   37050.00  ...
..                   ...         ...          ...        ...        ...  ...
695                  260       300.0     742500.0  111375.00  631125.00  ...
696                  260       300.0     163800.0   24570.00  139230.00  ...
697                    5         7.0       9576.0    1436.40    8139.60  ...
698                   10         7.0       5061.0     759.15    4301.85  ...
699                  250        12.0      21672.0    3250.80   18421.20  ...

       Profit       Date Month Number  Month Name  Year  Government  \
0    16185.00 2014-01-01            1     January  2014           1
1    13210.00 2014-01-01            1     January  2014           1
2    10890.00 2014-06-01            6        June  2014           0
3     4440.00 2014-06-01            6        June  2014           0
4    12350.00 2014-06-01            6        June  2014           0
..        ...        ...          ...         ...   ...         ...
695  12375.00 2014-03-01            3       March  2014           0
696   2730.00 2014-10-01           10     October  2014           0
697   1299.60 2014-02-01            2    February  2014           1
698    686.85 2014-04-01            4       April  2014           1
699  13003.20 2014-05-01            5         May  2014           0

     Midmarket  Channel Partners  Enterprise  Small Business
0            0                 0           0               0
1            0                 0           0               0
2            1                 0           0               0
3            1                 0           0               0
4            1                 0           0               0
..         ...               ...         ...             ...
695          0                 0           0               1
696          0                 0           0               1
697          0                 0           0               0
698          0                 0           0               0
699          0                 1           0               0

[700 rows x 21 columns]>

In [33]:
df.Product.unique()

<StringArray>
['Carretera', 'Montana', 'Paseo', 'Velo', 'VTT', 'Amarilla']
Length: 6, dtype: str

In [34]:
from sklearn.preprocessing import OneHotEncoder

In [3]:
encoder = OneHotEncoder( sparse_output=False )

In [35]:
encoded_df = encoder.fit_transform(df[['Product']])

C:\Users\mushr\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [36]:
print(encoded_df)

[1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 5 5 5 5 5 5
 5 4 4 4 4 4 4 4 0 0 0 0 0 0 0 0 3 3 3 5 4 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2
 3 3 3 3 3 3 3 3 3 5 5 5 5 5 4 4 4 4 4 4 4 4 0 0 1 1 1 1 1 2 2 2 2 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 5 5 5 5 5 5 5 5 4 4 4 4 4 4 0 0 0 0 0 0 0 1 1 1 1
 1 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 1 3 5 4 2 3 3 5 1 1 1 2 2
 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 5 5 5 4 4 4 4 0 0 0 0 0 2 3 3 3 3 5 4 0 1
 1 1 1 1 1 1 1 1 1 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 5 5 5 5 5 5 5
 5 5 5 4 4 4 4 4 4 0 0 0 0 3 1 1 1 1 1 1 1 2 2 2 2 3 3 3 5 5 5 5 5 5 5 4 4
 4 4 4 0 0 0 0 0 2 3 3 3 3 5 5 4 1 1 1 2 2 3 5 5 5 5 4 4 4 0 1 1 1 2 2 2 3
 3 3 3 3 3 3 3 3 3 5 5 5 5 5 5 5 4 4 4 0 0 0 0 0 2 2 3 0 1 1 1 2 2 2 2 2 2
 3 3 3 3 3 3 3 3 3 3 3 3 3 5 5 5 5 5 4 4 4 4 4 4 0 0 0 0 0 0 0 0 4 1 1 2 2
 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 5 5 5 5 5 5 4 4 4 4 4 4 4 4 0 0 0 0 1 1 1 1
 3 3 3 5 5 4 4 4 0 0 0 1 2 3 1 1 2 2 2 3 3 3 3 5 5 5 5 5 5 5 5 5 5 4 4 4 4
 4 4 4 4 0 0 0 0 0 0 0 0 0 1 3 3 5 5 4 4 0 0 1 1 1 1 1 1 2 2 2 3 3 3 3 3 3
 3 3 3 3 5 5 5 5 4 4 4 0 0 0 0 0 0 3 1 1 1 1 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3
 3 3 5 5 5 4 4 4 4 4 4 0 0 0 0 1 2 3 4 4 0 1 4 1 1 1 2 2 2 2 2 3 3 3 3 3 3
 3 3 3 3 3 3 5 5 5 5 5 5 5 5 4 4 0 0 0 0 1 1 1 1 2 2 3 3 3 3 4 0 0 1 1 1 1
 1 1 1 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 5 5 5 5 5 4 4 4 4 4 4 0 0 0 0 0 0 0 0
 1 1 1 2 3 3 3 3 3 3 3 3 3 3 3 3 5 5 5 5 5 5 4 4 4 4 4 4 4 0 0 2 3 4]

In [29]:
encoded_df = pd.DataFrame( encoded_df , columns=encoder.get_feature_names_out())

AttributeError: 'LabelEncoder' object has no attribute 'get_feature_names_out'

In [39]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(sparse_output=False)

In [40]:
encoded_df = encoder.fit_transform(df[['Product']])

In [43]:
encoded_df = pd.DataFrame(encoded_df, columns=encoder.get_feature_names_out())
encoded_df

,Product_Amarilla,Product_Carretera,Product_Montana,Product_Paseo,Product_VTT,Product_Velo
0,0.0,1.0,0.0,0.0,0.0,0.0
1,0.0,1.0,0.0,0.0,0.0,0.0
2,0.0,1.0,0.0,0.0,0.0,0.0
3,0.0,1.0,0.0,0.0,0.0,0.0
4,0.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...
695,1.0,0.0,0.0,0.0,0.0,0.0
696,1.0,0.0,0.0,0.0,0.0,0.0
697,0.0,0.0,1.0,0.0,0.0,0.0
698,0.0,0.0,0.0,1.0,0.0,0.0
699,0.0,0.0,0.0,0.0,1.0,0.0