In [1]:
# Standardization & Normalization

# Standardization:- center the data around mean(μ = 0) with a standerd division(σ = 1).(Range:-No fixed limits,Center :-centered at mean = 0,Outlieres:- less affected)
# Standardization (it is good to go with standardization if you have outlier in your dataset)
# z = x(Data)-μ(mean)/σ(std)

In [2]:
data = {
    'Empid':[x for x in range(101,111)],
    'Empsalary':[23445,78786,78987,932455,67554,78987,23244,67865,34554,67876]
}

In [3]:
import pandas as pd

In [4]:
# Scaling
# Salary : 10k, 1l, 10l /10l  => 0.01, 0.1, 1
# Age = 54, 67, 45 / 100      => 0.54, 0.67, 0.45

In [5]:
df = pd.DataFrame(data)

In [6]:
df

   Empid  Empsalary
0    101      23445
1    102      78786
2    103      78987
3    104     932455
4    105      67554
5    106      78987
6    107      23244
7    108      67865
8    109      34554
9    110      67876

In [7]:
df['scalesalary'] = (df['Empsalary']-df['Empsalary'].mean())/df['Empsalary'].std()

In [8]:
df

   Empid  Empsalary  scalesalary
0    101      23445    -0.439445
1    102      78786    -0.239992
2    103      78987    -0.239268
3    104     932455     2.836688
4    105      67554    -0.280473
5    106      78987    -0.239268
6    107      23244    -0.440169
7    108      67865    -0.279352
8    109      34554    -0.399407
9    110      67876    -0.279313

In [9]:
df.scalesalary.max()

np.float64(2.836688143149149)

In [10]:
df = df[df.scalesalary<df.scalesalary.max()]

In [11]:
df

   Empid  Empsalary  scalesalary
0    101      23445    -0.439445
1    102      78786    -0.239992
2    103      78987    -0.239268
4    105      67554    -0.280473
5    106      78987    -0.239268
6    107      23244    -0.440169
7    108      67865    -0.279352
8    109      34554    -0.399407
9    110      67876    -0.279313

In [12]:
from sklearn.preprocessing import StandardScaler

In [13]:
newdf = StandardScaler().fit_transform(df)

In [14]:
df

   Empid  Empsalary  scalesalary
0    101      23445    -0.439445
1    102      78786    -0.239992
2    103      78987    -0.239268
4    105      67554    -0.280473
5    106      78987    -0.239268
6    107      23244    -0.440169
7    108      67865    -0.279352
8    109      34554    -0.399407
9    110      67876    -0.279313

In [15]:
df.describe()

            Empid     Empsalary  scalesalary
count    9.000000      9.000000     9.000000
mean   105.666667  57922.000000    -0.315188
std      3.162278  23850.540801     0.085959
min    101.000000  23244.000000    -0.440169
25%    103.000000  34554.000000    -0.399407
50%    106.000000  67865.000000    -0.279352
75%    108.000000  78786.000000    -0.239992
max    110.000000  78987.000000    -0.239268

In [16]:
# Normalization(Min-Max Scalling):- Rescale data into a fixed range,usually between 0 and 1 
#(Range:- fixed[0,1], Center:-Scalling based on min/max, Outliers:-Highly affected)
# z = (x-min) / (max-min)

In [17]:
df = df[df['Empsalary']<500000]

In [18]:
df

   Empid  Empsalary  scalesalary
0    101      23445    -0.439445
1    102      78786    -0.239992
2    103      78987    -0.239268
4    105      67554    -0.280473
5    106      78987    -0.239268
6    107      23244    -0.440169
7    108      67865    -0.279352
8    109      34554    -0.399407
9    110      67876    -0.279313

In [19]:
df['scalesalary'] = (df['Empsalary'] - df['Empsalary'].min()) / (df['Empsalary'].max() - df['Empsalary'].min())

In [20]:
df

   Empid  Empsalary  scalesalary
0    101      23445     0.003606
1    102      78786     0.996394
2    103      78987     1.000000
4    105      67554     0.794898
5    106      78987     1.000000
6    107      23244     0.000000
7    108      67865     0.800477
8    109      34554     0.202895
9    110      67876     0.800675

In [23]:
df = df.drop(columns=['scalesalary'])

In [24]:
from sklearn.preprocessing import MinMaxScaler

In [25]:
df = MinMaxScaler().fit_transform(df)

In [26]:
df

array([[0.        , 0.00360583],
       [0.11111111, 0.99639417],
       [0.22222222, 1.        ],
       [0.44444444, 0.79489801],
       [0.55555556, 1.        ],
       [0.66666667, 0.        ],
       [0.77777778, 0.80047719],
       [0.88888889, 0.20289543],
       [1.        , 0.80067452]])